### ISSUE TITLE
defining 2 weave networks on one pod fails

### ISSUE THREAD

**Issue by yuvalif** [Huawei-PaaS/CNI-Genie#133]
I k8s setup with: flannel, weave and genie
using the following pod setup:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-weave-2
  annotations:
    cni: "weave,weave"
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```
I get an error message from genie:
```
Warning  FailedCreatePodSandBox  8m (x2717 over 2h)   kubelet, vm-18-80  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "22471ae954b9986f5a9b2eeee1fe3f52bf8cd4b40f286a3fd6e7d5f6cda0e80e" network for pod "nginx-weave-2": NetworkPlugin cni failed to set up pod "nginx-weave-2_default" network: CNI Genie Add IP internal error: CNI Genie error at addNetwork: could not create veth pair vethwepl22471ae-vethwepg22471ae: file exists, result: %!!(MISSING)s(<nil>)
```

Seems like veth pair with the same name is already created.
Note that creation of a pod with 2 flannel networks, or with weave and flannel works well on my setup.
