### ISSUE TITLE
update vendor/github.com/containernetworking/cni to newer version

### ISSUE THREAD

**Issue by yuvalif** [Huawei-PaaS/CNI-Genie#134]
The latest implementation does bot force IP to be defined.
See: https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L107
while the code under local "vendor", has this check:
https://github.com/Huawei-PaaS/CNI-Genie/blob/master/vendor/github.com/containernetworking/cni/pkg/types/current/types.go#L108

This prevents using Genie to add an L2 network to a pod, using a plugin without IPAM.

**Comment by sushanthakumar** [comment]
@yuvalif , yes, there are some modifications in latest cni. I also feel it is better to migrate to new one so that users will be able to realize the new cni offerings. 
We will do at the earliest. 
Meanwhile if you have your usecase (ie yaml, config files, steps  you used wherein above issue you observed), you can share with us. We will do basic test with this case once we finish the modifications
Thanks for bringing this issue out.

**Comment by yuvalif** [comment]
I have the following CNI I'm trying to use, it attaches an existing host bridge to a pod.
Here is a daemon set yaml for it:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-l2-bridge-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: l2-bridge-cni-plugin
spec:
  template:
    metadata:
      labels:
        tier: node
        app: l2-bridge-cni-plugin-cni-plugin
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: cni-l2-bridge-plugin
        image: quay.io/schseba/l2-bridge-cni-plugin:latest
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
```
Under the ```/etc/cni/net.d/``` directory I placed a configuration file for that L2 bridge CNI: ```10-red-bridge.conf```, note that it has an empty IPAM object, since no L3 connectivity is provided by that CNI.
```
{
        "name": "my-red-net",
        "cniVersion": "0.3.0",
        "type": "l2-bridge",
        "bridge": "red",
        "ipam": {}
}
```
In my usecase, I run a virtual machine inside that pod, and connect it to the pod interfaces that was added. Inside the virtual machine I can get L3 connectivity by using DHCP on that network.
